4500zenja1/Creating file handler
parys/internship pull request #116
Opened 2021-08-07 14:18 UTC by 4500zenja1

The first version of file handler is created + web.config is created for correct work of it, too.

It is expected to update this commit to fix and add new features to meet the goals.

2021-08-08 15:15 UTC, DShcharbakou approved these changes

2021-08-08 15:15 UTC, DShcharbakou commented on Elevel/Elevel.Api/Controllers/FileController.cs
> +                return Ok(new { formFiles.Count, Size = _fileService.SizeConverter(formFiles.Sum(f => f.Length)) });
I think it's not necessary. You can return just Ok

2021-08-08 15:15 UTC, DShcharbakou commented on Elevel/Application/Features/FileFeatures/FileCommands.cs
> +        public void UploadFile(List<IFormFile> files, string subDirectory)
subDirectory param does not need because User will not send path when he will upload the file.

2021-08-09 14:08 UTC, DShcharbakou commented on Elevel/Elevel.Api/Controllers/FileController.cs
> +             var Zip = _fileService.DownloadFiles();
for local variables use lowercase _zip_

2021-08-09 14:11 UTC, DShcharbakou commented on Elevel/Elevel.Infrastructure.Services/Implementation/FileService.cs
> +                var filePath = "example.txt";
var filePath = string.Empty;

2021-08-09 14:25 UTC, DShcharbakou commented on Elevel/Elevel.Api/Controllers/FileController.cs
> +        public IActionResult Download()
need param for path and return single file

2021-08-09 14:28 UTC, DShcharbakou commented on Elevel/Elevel.Infrastructure.Services/Implementation/FileService.cs
> +        public FileZip DownloadFiles()
It needs relative path for downloading single file. For example "Audition/file2021_02_29-18_44_55"

2021-08-09 14:31 UTC, DShcharbakou commented on Elevel/Elevel.Infrastructure.Services/Implementation/FileService.cs
> +            Directory.CreateDirectory(target);
only If this folder doesn't exist

2021-08-09 14:32 UTC, DShcharbakou commented on Elevel/Application/Interfaces/IFileService.cs
> +        string SizeConverter(long bytes);
SizeConverter - not needed

2021-08-09 14:32 UTC, DShcharbakou requested changes
Need changes

2021-08-09 14:35 UTC, DShcharbakou commented on Elevel/Elevel.Infrastructure.Services/Implementation/FileService.cs
> +        public FileZip DownloadFiles(string fromDirectory)
instead fromDirectory needs fromFilePath
For example "myFile2021_02_19_16_00_50.mp3"

2021-08-10 17:46 UTC, DShcharbakou approved these changes

2021-08-10 17:46 UTC, DShcharbakou commented on Elevel/Elevel.Infrastructure.Services/Implementation/FileService.cs
> +            var target = @"wwwroot\files";
It could be constant

2021-08-10 17:46 UTC, DShcharbakou commented on Elevel/Elevel.Infrastructure.Services/Implementation/FileService.cs
> +            var data = net.DownloadData(Path.Combine(@"wwwroot\files", fileName));
you can use this File.ReadAllBytes(fileName); instead of WebClient

2021-08-10 17:46 UTC, DShcharbakou commented on Elevel/Elevel.Infrastructure.Services/Implementation/FileService.cs
> +            var content = new System.IO.MemoryStream(data);
var content = new MemoryStream(data);

2021-08-10 17:48 UTC, DShcharbakou commented on Elevel/Elevel.Api/Controllers/FileController.cs
> +        public IActionResult Download([Required] string fileName)
instead fileName use filePath

2021-08-10 19:28 UTC, DShcharbakou approved these changes

2021-08-10 19:30 UTC, parys commented on Elevel/Elevel.Api/wwwroot/files/myFile2021_08_10-22_22_15.json
> +{
do you need this file?

2021-08-10 19:31 UTC, 4500zenja1 commented on Elevel/Elevel.Api/wwwroot/files/myFile2021_08_10-22_22_15.json
> +{
No, I forgot to delete it :oops:

2021-08-10 19:33 UTC, parys requested changes

2021-08-10 19:33 UTC, parys commented on Elevel/Elevel.Infrastructure.Services/Implementation/FileService.cs
> +            const string target = @"wwwroot\files";
it's bad practice to have hadrdcoded separator. Pleae use Path.Combine("wwwroot", "files") + create readonly field to avoid path duplication

2021-08-10 19:33 UTC, parys commented on Elevel/Elevel.Infrastructure.Services/Implementation/FileService.cs
> +            var file = File.ReadAllBytes(Path.Combine(@"wwwroot\files", fileName));
it's bad practice to have hadrdcoded separator. Pleae use Path.Combine("wwwroot", "files") + create readonly field to avoid path duplication

2021-08-10 19:33 UTC, parys commented on Elevel/Elevel.Infrastructure.Services/Implementation/FileService.cs
> +            _hostingEnvironment = hostingEnvironment;
as I see you not using it

2021-08-10 19:33 UTC, parys commented on Elevel/Elevel.Api/Controllers/FileController.cs
> +    public class FileController : BaseApiController
do you miss Authorize ?

2021-08-10 19:33 UTC, DShcharbakou submitted a review, later dismissed

2021-08-10 20:00 UTC, parys approved these changes

2021-08-10 20:30 UTC, merged