Andrey Rohau / Get Coaches Fix
parys/internship pull request #118
Opened 2021-08-08 16:28 UTC by andreyrogov8

2021-08-08 16:52 UTC, DShcharbakou requested changes

2021-08-08 16:52 UTC, DShcharbakou commented on Elevel/Application/Features/UserFeatures/GetCoachesQuery.cs
> +                    var coach = coachList.FirstOrDefault(x => x.Id == testcount.Key);
setup this filter after grouping

2021-08-09 14:38 UTC, DShcharbakou approved these changes

2021-08-09 18:33 UTC, rinchan603 approved these changes

2021-08-09 18:36 UTC, Evgenij-Kovpak approved these changes

2021-08-09 18:37 UTC, merged