Andrey Rohau / email notification fix
parys/internship pull request #132
Opened 2021-08-15 12:11 UTC by andreyrogov8

2021-08-16 14:51 UTC, 4500zenja1 approved these changes

2021-08-16 14:53 UTC, parys commented on Elevel/Application/Features/TestCommands/SubmitTestCommand.cs
> +                    .Count();
can be instead of where

2021-08-16 15:02 UTC, parys requested changes

2021-08-16 15:02 UTC, parys commented on Elevel/Elevel.Infrastructure.Services/Implementation/MailService.cs
> +                        _smtpClient.Disconnect(true);
code duplication

2021-08-16 15:02 UTC, parys commented on Elevel/Elevel.Infrastructure.Services/Jobs/EmailJob.cs
> +            var userIds = await _context.Tests
it will be good to have 2 methods: 1 for send missedDeadlineUserIds and second for UsersEmailNotification

2021-08-16 15:02 UTC, parys commented on Elevel/Elevel.Infrastructure.Services/Jobs/EmailScheduler.cs
> +                .StartAt(DateBuilder.DateOf(12,30,0,17,8))
magic numbers

2021-08-16 18:18 UTC, DShcharbakou approved these changes

2021-08-16 18:18 UTC, DShcharbakou commented on Elevel/Elevel.Infrastructure.Services/Implementation/MailService.cs
> +        public string SendMessage(Guid receiverId, string subject, string body)
instead receiverId you need send userEmail

2021-08-16 18:18 UTC, DShcharbakou commented on Elevel/Elevel.Infrastructure.Services/Implementation/MailService.cs
> +        private string UsersEmailNotification(List<Guid> receiverIds, string subject, string body)
instead List<Guid> receiverIds you need send List<string> userEmails

2021-08-16 18:18 UTC, DShcharbakou commented on Elevel/Elevel.Infrastructure.Services/Implementation/MailService.cs
> +                _message.To.Add(MailboxAddress.Parse(receiverEmail));
You should use AddRange instead of loop

2021-08-16 18:18 UTC, DShcharbakou commented on Elevel/Elevel.Infrastructure.Services/Implementation/MailService.cs
> +                var Users = _userManager.Users.Where(x => pair.UserIds.Contains(x.Id));
Bad practice. Database queries in a loop.

2021-08-16 18:18 UTC, DShcharbakou commented on Elevel/Elevel.Infrastructure.Services/Implementation/MailService.cs
> +                }
If hrEmail doesn't exist but there are users?

2021-08-16 18:18 UTC, DShcharbakou commented on Elevel/Elevel.Infrastructure.Services/Implementation/MailService.cs
> +                _message.To.Add(MailboxAddress.Parse(hrEmail));
AddRange

2021-08-16 18:18 UTC, DShcharbakou commented on Elevel/Elevel.Infrastructure.Services/Implementation/MailService.cs
> +                        _smtpClient.Send(_message);
Send in the loop it's not a good idea. Need revise this method. It can be dividing for few smaller methods.

2021-08-17 09:07 UTC, andreyrogov8 commented on Elevel/Elevel.Api/appsettings.Development.json
> +  //}
I removed these comments

2021-08-17 09:07 UTC, andreyrogov8 commented on Elevel/Elevel.Infrastructure.Services/Implementation/MailService.cs
> +                }
See previous validation

2021-08-17 09:08 UTC, parys approved these changes

2021-08-17 09:19 UTC, merged