4500zenja1/Added sending messages for some Test commands
parys/internship pull request #134
Opened 2021-08-16 12:08 UTC by 4500zenja1

2021-08-16 12:55 UTC, DShcharbakou requested changes

2021-08-16 12:55 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/AssignTestCommand.cs
> +            public Handler(IApplicationDbContext context, IMapper mapper, UserManager<User> userManager, IMailService mail)
mail -> mailService

2021-08-16 12:55 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/AssignTestCommand.cs
> +                    "text like 'You have an assigned to you test now'");
It will be changed. This case we discussed on the daily meeting

2021-08-16 12:55 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/AssignTestForCoachCommand.cs
> +                    "text like 'You as a coach have an assinged to you test now'");
It will be changed. This case we discussed on the daily meeting

2021-08-16 12:55 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CheckTestCommand.cs
> +                        "text like 'The test assigned to user by you was checked");
It will be changed. This case we discussed on the daily meeting

2021-08-16 12:55 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CheckTestCommand.cs
> +                    "text like 'The test you completed is now checked");
It will be changed. This case we discussed on the daily meeting

2021-08-16 12:55 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/SubmitTestCommand.cs
> +                    "text like 'Admin, you have submitted the test to...!'");
It will be changed. This case we discussed on the daily meeting

2021-08-16 12:55 UTC, DShcharbakou commented on Elevel/Application/Interfaces/IMailService.cs
> +        public string UsersEmailNotification(UserManager<User> userManager, List<Guid> receiverIds, string subject, string body);
Contract will be changed. This case we discussed on the daily meeting

2021-08-16 12:55 UTC, DShcharbakou commented on Elevel/Elevel.Api/Controllers/EmailNotificationController.cs
> +    public class EmailNotificationController : ControllerBase
Why do you need EmailNotificationController?

2021-08-16 12:55 UTC, DShcharbakou commented on Elevel/Elevel.Api/appsettings.Development.json
> +  //},
mmm?

2021-08-16 12:55 UTC, DShcharbakou commented on Elevel/Elevel.Infrastructure.Services/Implementation/MailService.cs
> +        public string SendMessage(UserManager<User> userManager, Guid receiverId, string subject, string body)
Contract will be changed. This case we discussed on the daily meeting

2021-08-17 14:09 UTC, 4500zenja1 commented
I think it's better to open a new PR rather than support this one, especially after changes by other PRs.

2021-08-17 14:09 UTC, closed without merging