create EmailNotification class
parys/internship pull request #85
Opened 2021-07-23 14:00 UTC by Evgenij-Kovpak

2021-07-23 19:27 UTC, 4500zenja1 approved these changes

2021-07-23 20:45 UTC, andreyrogov8 submitted a review, later dismissed

2021-07-24 12:20 UTC, DShcharbakou requested changes
Whitout merging

2021-07-28 15:07 UTC, DShcharbakou requested changes

2021-08-15 10:55 UTC, closed without merging

2021-08-15 10:55 UTC, andreyrogov8 commented
No longer need