Andrey Rohau / Create test, GetAll + validation, Updated db + migration
parys/internship pull request #90
Opened 2021-07-26 17:03 UTC by andreyrogov8

2021-07-26 20:29 UTC, DShcharbakou requested changes

2021-07-26 20:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                if (await _userManager.Users.FirstOrDefaultAsync(x => x.Id == request.UserId).ConfigureAwait(false) == null)
_userManager.Users.Any(x => x.Id == request.UserId)

2021-07-26 20:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    };
In this case instead response I supposed using exception e.g. throw EntityNotFoundException("UserId is not found"). Or you can create your own exception e.g. ValidationException or BusinessException

2021-07-26 20:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                var Hr = await _userManager.Users.FirstOrDefaultAsync(x => x.Id == request.HrId).ConfigureAwait(false);
Any()

2021-07-26 20:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    };
throw appropriate exception

2021-07-26 20:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    };
throw appropriate exception

2021-07-26 20:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    };
throw appropriate exception

2021-07-26 20:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    };
throw appropriate exception

2021-07-26 20:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    };
throw appropriate exception

2021-07-26 20:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                var auditions = await _context.Auditions.AsNoTracking().Where(x => x.Level == request.Level && !x.Deleted).ToListAsync().ConfigureAwait(false);
!x.Deleted move it to fluent configuration

2021-07-26 20:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    };
throw appropriate exception

2021-07-26 20:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                var topics = await _context.Topics.AsNoTracking().Where(x => x.Level == request.Level && !x.Deleted).ToListAsync().ConfigureAwait(false);
!x.Deleted move it

2021-07-26 20:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    };
throw appropriate exception

2021-07-26 20:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    };
throw appropriate exception

2021-07-26 20:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    };
throw appropriate exception

2021-07-26 20:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                .Where(x => x.Level == test.Level && x.AuditionId == null && !x.Deleted).ToListAsync().ConfigureAwait(false);
!x.Deleted move it

2021-07-27 08:15 UTC, andreyrogov8 commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                if (await _userManager.Users.FirstOrDefaultAsync(x => x.Id == request.UserId).ConfigureAwait(false) == null)
_userManager.Users.Any(x => x.Id == request.UserId)

2021-07-27 20:36 UTC, DShcharbakou requested changes
One important thing. On real project you shouldn't update packages after each pull request because sometimes not all of packagies will be works fine on new version as worked on a previous version. In this case usually make separete task for updating packagies.

2021-07-27 20:36 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/AssignTestCommand.cs
> +                if (questions.Count() < 12)
magic number

2021-07-27 20:36 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/AssignTestCommand.cs
> +                if (questions.Count() < 10)
magic number

2021-07-27 20:36 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +
a lot of blank lines. It looks not so good.

2021-07-27 20:36 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                if (!_userManager.Users.Any(x => x.Id == request.UserId))
use async version

2021-07-27 20:36 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    throw new NotFoundException("User");
You need to use message with more details in exception.

2021-07-27 20:36 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                if (_context.Tests.Any(x => x.UserId == request.UserId
use async version

2021-07-27 20:36 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +
blank line does not needed

2021-07-27 20:36 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                if (questions.Count() < 10)
magic number

2021-07-27 20:36 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                if (questions.Count() < 12)
magic number

2021-07-27 20:36 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/GetAllTestsQuery.cs
> +                    Results = await tests.Skip(request.SkipCount()).Take(request.PageSize).ProjectTo<TestDTO>(_mapper.ConfigurationProvider).OrderBy(x => x.TestNumber).ToListAsync().ConfigureAwait(fa
it's not readable. You can use few lines for this expression

2021-07-27 20:36 UTC, DShcharbakou commented on Elevel/Application/Infrastructure/ValidationException.cs
> +        }
Best practice is use three overloads
https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-create-user-defined-exceptions

2021-07-28 16:50 UTC, DShcharbakou approved these changes

2021-07-28 16:54 UTC, 4500zenja1 approved these changes

2021-07-28 17:00 UTC, merged