Andrey Rohau / Create test full response
parys/internship pull request #95
Opened 2021-07-29 16:49 UTC by andreyrogov8

2021-07-29 18:43 UTC, DShcharbakou requested changes

2021-07-29 18:43 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    var question = await _context.Questions.FirstOrDefaultAsync(x => x.Id == testQuestion.QuestionId).ConfigureAwait(false);
database queries in a loop it's a bad practice. You should find solution with one query to the DB.

2021-07-29 18:43 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    question.Answers = await GetAnswerDtosAsync(question.Id).ConfigureAwait(false);
database queries in a loop it's a bad practice. You should find solution with one query to the DB.

2021-07-29 18:43 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
>                      _context.TestQuestions.Add(testQuestion);
database queries in a loop it's a bad practice. You should find solution with one query to the DB.

2021-07-30 08:24 UTC, ristomin submitted a review, later dismissed

2021-07-30 10:29 UTC, DShcharbakou requested changes

2021-07-30 10:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                return fileteredQuestions;
In this method you can do something like this:
`
var testQuestionIds = testQuestions.Select(x => x.QuestionId);
return await _context.Questions.AsNoTracking().Where(x => x.AuditionId == auditionId && testQuestionIds.Contains(x.Id)).ToListAsync().ConfigureAwait(false);
`

2021-07-30 10:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    question.Answers = await GetAnswerDtosAsync(question.Id, answerList).ConfigureAwait(false);
You should configurate mapping for List\<QuestionDto\> -> List\<Question\>

2021-07-30 10:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    .ToListAsync().ConfigureAwait(false);
You should do it in one query in AddAnswersAsync() line 229

2021-07-30 10:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                    questionDtos.Add(_mapper.Map<QuestionDto>(question));
You should configure List\<QuestionDto\> -> List\<Question\>

2021-07-30 10:29 UTC, DShcharbakou commented on Elevel/Application/Features/TestCommands/CreateTestCommand.cs
> +                return topic;
just use 
`return await _context.Topics.ProjectTo<TopicDto>(_mapper.ConfigurationProvider).FirstOrDefaultAsync(x => x.Id == topicId).ConfigureAwait(false);`

2021-07-30 19:29 UTC, parys commented on Elevel/Application/Profiles/TestProfile.cs
> +            CreateMap<Test, GetTestByIdQuery.Response>();
duplicate 23-24

2021-07-30 19:30 UTC, parys approved these changes

2021-07-30 19:36 UTC, ristomin approved these changes

2021-07-30 19:46 UTC, DShcharbakou approved these changes

2021-07-30 19:47 UTC, merged